# Exercise 7: Add new item to list after a specified item
#
# Write a program to add item 7000 after 6000 in the following Python List
#
# Given:
#
# list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
#
# Expected output:
#
# [10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]

for sublist in list1:
    if isinstance(sublist, list):
        for subsublist in sublist:
            if isinstance(subsublist, list) and 6000 in subsublist:
                subsublist.append(7000)


print(f"Generated by ChatGPT: {list1}")

# FROM SOLUTIONS:

# understand indexing
# list1[0] = 10
# list1[1] = 20
# list1[2] = [300, 400, [5000, 6000], 500]
# list1[2][2] = [5000, 6000]
# list1[2][2][1] = 6000

# solution
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
print(f"Solution by book: {list1}")

# MARTIN: može li se ovo napraviti da uvijek vrijedi, generički napisati?